branches:
  only:
    - master

matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      before_script:
        - cd frontend
      script:
        - yarn --silent
        - yarn run build
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: frontend/build
          on:
            branch: master