#zeit, deploy to pages
#need privacy policy
#babel, nodemon
#api
#put on cv
#make it into an app too
#upload photo or take one
#share card
#global error handler
#give everything keys and go through console errors and fix
#figure out how all the context and hook stuff working - https://medium.com/simply/state-management-with-react-hooks-and-context-api-at-10-lines-of-code-baf6be8302c
#check all objects with keys using either constant key names or typed in each time
#go through todos and comments