branches:
  only:
    - master

matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      before_script:
        - cd web
      script:
        #dockerise it instead of this
        - yarn --silent
        - yarn run build
    - language: node_js
      services:
        - docker
      before_script:
        - cd api
      script:
        - docker build .

            #dockerise website and api
            #send docker containers somewhere
            #now sh for api - fail on eslint
